###Numpy Operations:  

Problem Statement: To learn how to use NumPy for creating arrays, performing basic array operations, and conducting numerical computations through analyzing temperature data.

Scenario: You are given a list of daily average temperatures (in degrees Celsius) recorded over two weeks. Your task is to use NumPy to analyze this data.


In [ ]:
import numpy as np

1.	Create NumPy Arrays

In [ ]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
temperatures_w1

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])


2.	Inspection and Properties:


In [ ]:
#	Inspect the shape of the temperatures_w1 array.
np.shape(temperatures_w1)

(7,)

In [ ]:
#	Determine the data type of the temperatures_w1 array elements
temperatures_w1.dtype

dtype('float64')

In [ ]:
#	Find out the number of elements in the temperatures_w1 array
temperatures_w1.size

7

3.	Array Operations:

In [ ]:
#	Convert the temperatures_w1 from Celsius to Fahrenheit using the formula: Fahrenheit = (Celsius * 9/5) + 32
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
Fahrenheit = (temperatures_w1 * 9/5) + 32
print(Fahrenheit)

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [ ]:
#	Find the maximum and minimum temperatures of the week.
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
maximum = np.max(temperatures_w1)
print("maximum temperatures of the week",maximum)

minimum = np.min(temperatures_w1)
print("minimum temperatures of the week",minimum )

maximum temperatures of the week 26.1
minimum temperatures of the week 20.8


In [ ]:
# Calculate the mean (average) temperature of the week.
average = np.mean(temperatures_w1 )
print("average temperatures of the week",average )

average temperatures of the week 23.542857142857144



4.	Array Slicing and Indexing:


In [ ]:
#Extract the temperatures for the first three days of the week
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
temperatures_w1[:3]

array([22.5, 25.3, 20.8])

In [ ]:
#Extract the temperatures for the weekend (last two days).
temperatures_w1[-2:]

array([24.8, 21.9])

In [ ]:
#	Extract the temperatures for the middle three days of the week.
temperatures_w1[2:5]

array([20.8, 23.4, 26.1])

5.	Create a 2D Array:

Create a 2D NumPy array named temperatures where each row represents temperatures for a different week:


In [ ]:
temperatures = np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])
temperatures


array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

6.	Inspect and Slice the 2D Array:

In [ ]:
#	Inspect and print the shape, data type, and total number of elements in the temperatures array.
temperatures.shape


(2, 7)

In [ ]:
temperatures.dtype

dtype('float64')

In [ ]:
temperatures.size

14

In [ ]:
#	Extract and print:
#	The temperatures for the first week (Row 1).
temperatures[0]

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [ ]:
#	The temperatures for the second week (Row 2).
temperatures[1]

array([19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1])

In [ ]:
#The temperatures for the first three days of each week.
temperatures[:,:3]

array([[22.5, 25.3, 20.8],
       [19.2, 22.5, 21.3]])

In [ ]:
#The temperatures for the weekends (last two days) of both weeks.
temperatures[:,5:]


array([[24.8, 21.9],
       [22.8, 20.1]])